app = 'trace-dojo'
primary_region = 'nrt'

[[mounts]]
  source = "db"
  destination = "/app/prisma/mount"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
