name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

concurrency:
  group: autofix-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: yarn install
      - run: yarn cleanup
      - run: yarn run build
      - uses: autofix-ci/action@v1
