name: Deploy production
on:
  workflow_dispatch:
  release:
    types:
      - published
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy:
    uses: exKAZUu-Research/reusable-workflows/.github/workflows/deploy.yml@main
    with:
      environment: production
    secrets:
      DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY }}
