name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - wbfy
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  test:
    uses: exKAZUu-Research/reusable-workflows/.github/workflows/test.yml@main
    with:
      ci_label: large
      github_hosted_runner: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
